import type {
  DarkThemePresetId,
  LightThemePresetId,
  ThemeAppearance,
  ThemePresetId,
} from "../../../types";

export type VsCodeThemeColors = Record<string, string>;

export type VsCodeThemePresetDefinition = {
  id: ThemePresetId;
  appearance: ThemeAppearance;
  labelKey: string;
  colors: VsCodeThemeColors;
};

export const DEFAULT_LIGHT_THEME_PRESET_ID: LightThemePresetId =
  "vscode-light-modern";
export const DEFAULT_DARK_THEME_PRESET_ID: DarkThemePresetId =
  "vscode-dark-modern";

export const LIGHT_THEME_PRESET_IDS = [
  "vscode-light-modern",
  "vscode-light-plus",
  "vscode-github-light",
  "vscode-solarized-light",
] as const satisfies readonly LightThemePresetId[];

export const DARK_THEME_PRESET_IDS = [
  "vscode-dark-modern",
  "vscode-dark-plus",
  "vscode-github-dark",
  "vscode-github-dark-dimmed",
  "vscode-one-dark-pro",
  "vscode-monokai",
  "vscode-solarized-dark",
] as const satisfies readonly DarkThemePresetId[];

export const ALL_THEME_PRESET_IDS = [
  ...LIGHT_THEME_PRESET_IDS,
  ...DARK_THEME_PRESET_IDS,
] as const satisfies readonly ThemePresetId[];

const DARK_MODERN_COLORS: VsCodeThemeColors = {
  foreground: "#cccccc",
  descriptionForeground: "#9d9d9d",
  "editor.background": "#1f1f1f",
  "editor.foreground": "#cccccc",
  "sideBar.background": "#181818",
  "sideBar.foreground": "#cccccc",
  "panel.background": "#181818",
  "panel.border": "#2b2b2b",
  "input.background": "#313131",
  "input.foreground": "#cccccc",
  "input.border": "#3c3c3c",
  "button.background": "#0078d4",
  "button.foreground": "#ffffff",
  "button.secondaryBackground": "#313131",
  "button.secondaryForeground": "#cccccc",
  "dropdown.background": "#313131",
  "dropdown.border": "#3c3c3c",
  "editorWidget.background": "#202020",
  "list.hoverBackground": "#242424",
  "list.activeSelectionBackground": "#04395e",
  "list.activeSelectionForeground": "#ffffff",
  "activityBar.background": "#181818",
  "activityBar.foreground": "#d7d7d7",
  "statusBar.background": "#181818",
  "statusBar.foreground": "#cccccc",
  "titleBar.activeBackground": "#181818",
  "titleBar.activeForeground": "#cccccc",
  "terminal.background": "#1f1f1f",
  "terminal.foreground": "#cccccc",
  "terminal.selectionBackground": "#264f78",
  "terminalCursor.foreground": "#cccccc",
  "editorLineNumber.foreground": "#6e7681",
  "editorGutter.addedBackground": "#2ea043",
  "editorGutter.modifiedBackground": "#0078d4",
  "editorGutter.deletedBackground": "#f85149",
  "textLink.foreground": "#4daafc",
  "badge.background": "#616161",
  "badge.foreground": "#f8f8f8",
};

const DARK_PLUS_COLORS: VsCodeThemeColors = {
  foreground: "#cccccc",
  descriptionForeground: "#969696",
  "editor.background": "#1e1e1e",
  "editor.foreground": "#d4d4d4",
  "sideBar.background": "#252526",
  "sideBar.foreground": "#cccccc",
  "panel.background": "#1e1e1e",
  "panel.border": "#2b2b2b",
  "input.background": "#3c3c3c",
  "input.foreground": "#cccccc",
  "input.border": "#3c3c3c",
  "button.background": "#0e639c",
  "button.foreground": "#ffffff",
  "button.secondaryBackground": "#3a3d41",
  "button.secondaryForeground": "#cccccc",
  "dropdown.background": "#3c3c3c",
  "dropdown.border": "#3c3c3c",
  "editorWidget.background": "#252526",
  "list.hoverBackground": "#2a2d2e",
  "list.activeSelectionBackground": "#094771",
  "list.activeSelectionForeground": "#ffffff",
  "activityBar.background": "#333333",
  "activityBar.foreground": "#ffffff",
  "statusBar.background": "#007acc",
  "statusBar.foreground": "#ffffff",
  "titleBar.activeBackground": "#3c3c3c",
  "titleBar.activeForeground": "#cccccc",
  "terminal.background": "#1e1e1e",
  "terminal.foreground": "#cccccc",
  "terminal.selectionBackground": "#264f78",
  "terminalCursor.foreground": "#aeafad",
  "editorLineNumber.foreground": "#858585",
  "editorGutter.addedBackground": "#2ea043",
  "editorGutter.modifiedBackground": "#007acc",
  "editorGutter.deletedBackground": "#f14c4c",
  "textLink.foreground": "#3794ff",
  "badge.background": "#4d4d4d",
  "badge.foreground": "#ffffff",
};

const LIGHT_MODERN_COLORS: VsCodeThemeColors = {
  foreground: "#3b3b3b",
  descriptionForeground: "#3b3b3b",
  "editor.background": "#ffffff",
  "editor.foreground": "#3b3b3b",
  "sideBar.background": "#f8f8f8",
  "sideBar.foreground": "#3b3b3b",
  "panel.background": "#f8f8f8",
  "panel.border": "#e5e5e5",
  "input.background": "#ffffff",
  "input.foreground": "#3b3b3b",
  "input.border": "#cecece",
  "button.background": "#005fb8",
  "button.foreground": "#ffffff",
  "button.secondaryBackground": "#e5e5e5",
  "button.secondaryForeground": "#3b3b3b",
  "dropdown.background": "#ffffff",
  "dropdown.border": "#cecece",
  "editorWidget.background": "#f8f8f8",
  "list.hoverBackground": "#f2f2f2",
  "list.activeSelectionBackground": "#e8e8e8",
  "list.activeSelectionForeground": "#000000",
  "activityBar.background": "#f8f8f8",
  "activityBar.foreground": "#1f1f1f",
  "statusBar.background": "#f8f8f8",
  "statusBar.foreground": "#3b3b3b",
  "titleBar.activeBackground": "#f8f8f8",
  "titleBar.activeForeground": "#1e1e1e",
  "terminal.background": "#ffffff",
  "terminal.foreground": "#3b3b3b",
  "terminal.selectionBackground": "#add6ff",
  "terminalCursor.foreground": "#005fb8",
  "editorLineNumber.foreground": "#6e7681",
  "editorGutter.addedBackground": "#2ea043",
  "editorGutter.modifiedBackground": "#005fb8",
  "editorGutter.deletedBackground": "#f85149",
  "textLink.foreground": "#005fb8",
  "badge.background": "#cccccc",
  "badge.foreground": "#3b3b3b",
};

const LIGHT_PLUS_COLORS: VsCodeThemeColors = {
  foreground: "#3b3b3b",
  descriptionForeground: "#616161",
  "editor.background": "#ffffff",
  "editor.foreground": "#000000",
  "sideBar.background": "#f3f3f3",
  "sideBar.foreground": "#3b3b3b",
  "panel.background": "#ffffff",
  "panel.border": "#d4d4d4",
  "input.background": "#ffffff",
  "input.foreground": "#3b3b3b",
  "input.border": "#cecece",
  "button.background": "#007acc",
  "button.foreground": "#ffffff",
  "button.secondaryBackground": "#ececec",
  "button.secondaryForeground": "#000000",
  "dropdown.background": "#ffffff",
  "dropdown.border": "#cecece",
  "editorWidget.background": "#f3f3f3",
  "list.hoverBackground": "#e8e8e8",
  "list.activeSelectionBackground": "#cce6ff",
  "list.activeSelectionForeground": "#000000",
  "activityBar.background": "#f3f3f3",
  "activityBar.foreground": "#424242",
  "statusBar.background": "#007acc",
  "statusBar.foreground": "#ffffff",
  "titleBar.activeBackground": "#dddddd",
  "titleBar.activeForeground": "#333333",
  "terminal.background": "#ffffff",
  "terminal.foreground": "#3b3b3b",
  "terminal.selectionBackground": "#add6ff",
  "terminalCursor.foreground": "#000000",
  "editorLineNumber.foreground": "#237893",
  "editorGutter.addedBackground": "#2ea043",
  "editorGutter.modifiedBackground": "#007acc",
  "editorGutter.deletedBackground": "#cd3131",
  "textLink.foreground": "#006ab1",
  "badge.background": "#c4c4c4",
  "badge.foreground": "#333333",
};

const GITHUB_LIGHT_COLORS: VsCodeThemeColors = {
  foreground: "#1f2328",
  descriptionForeground: "#57606a",
  "editor.background": "#ffffff",
  "editor.foreground": "#1f2328",
  "sideBar.background": "#f6f8fa",
  "sideBar.foreground": "#1f2328",
  "panel.background": "#ffffff",
  "panel.border": "#d0d7de",
  "input.background": "#ffffff",
  "input.foreground": "#1f2328",
  "input.border": "#d0d7de",
  "button.background": "#0969da",
  "button.foreground": "#ffffff",
  "button.secondaryBackground": "#f6f8fa",
  "button.secondaryForeground": "#1f2328",
  "dropdown.background": "#ffffff",
  "dropdown.border": "#d0d7de",
  "editorWidget.background": "#ffffff",
  "list.hoverBackground": "#f3f4f6",
  "list.activeSelectionBackground": "#ddf4ff",
  "list.activeSelectionForeground": "#0b3d91",
  "activityBar.background": "#f6f8fa",
  "activityBar.foreground": "#24292f",
  "statusBar.background": "#f6f8fa",
  "statusBar.foreground": "#57606a",
  "titleBar.activeBackground": "#ffffff",
  "titleBar.activeForeground": "#1f2328",
  "terminal.background": "#ffffff",
  "terminal.foreground": "#1f2328",
  "terminal.selectionBackground": "#b6e3ff",
  "terminalCursor.foreground": "#0969da",
  "editorLineNumber.foreground": "#8c959f",
  "editorGutter.addedBackground": "#1a7f37",
  "editorGutter.modifiedBackground": "#0969da",
  "editorGutter.deletedBackground": "#cf222e",
  "textLink.foreground": "#0969da",
  "badge.background": "#d0d7de",
  "badge.foreground": "#1f2328",
};

const SOLARIZED_LIGHT_COLORS: VsCodeThemeColors = {
  foreground: "#657b83",
  descriptionForeground: "#6c7f86",
  "editor.background": "#fdf6e3",
  "editor.foreground": "#586e75",
  "sideBar.background": "#eee8d5",
  "sideBar.foreground": "#586e75",
  "panel.background": "#f7f0dd",
  "panel.border": "#d8cfb5",
  "input.background": "#fdf6e3",
  "input.foreground": "#586e75",
  "input.border": "#cfc7ad",
  "button.background": "#268bd2",
  "button.foreground": "#fdf6e3",
  "button.secondaryBackground": "#eee8d5",
  "button.secondaryForeground": "#586e75",
  "dropdown.background": "#fdf6e3",
  "dropdown.border": "#cfc7ad",
  "editorWidget.background": "#f7f0dd",
  "list.hoverBackground": "#f1ead7",
  "list.activeSelectionBackground": "#dce8ef",
  "list.activeSelectionForeground": "#073642",
  "activityBar.background": "#eee8d5",
  "activityBar.foreground": "#586e75",
  "statusBar.background": "#eee8d5",
  "statusBar.foreground": "#586e75",
  "titleBar.activeBackground": "#fdf6e3",
  "titleBar.activeForeground": "#586e75",
  "terminal.background": "#fdf6e3",
  "terminal.foreground": "#586e75",
  "terminal.selectionBackground": "#dce8ef",
  "terminalCursor.foreground": "#268bd2",
  "editorLineNumber.foreground": "#93a1a1",
  "editorGutter.addedBackground": "#859900",
  "editorGutter.modifiedBackground": "#b58900",
  "editorGutter.deletedBackground": "#dc322f",
  "textLink.foreground": "#268bd2",
  "badge.background": "#e0d8be",
  "badge.foreground": "#586e75",
};

const GITHUB_DARK_COLORS: VsCodeThemeColors = {
  foreground: "#c9d1d9",
  descriptionForeground: "#8b949e",
  "editor.background": "#0d1117",
  "editor.foreground": "#c9d1d9",
  "sideBar.background": "#010409",
  "sideBar.foreground": "#c9d1d9",
  "panel.background": "#0d1117",
  "panel.border": "#30363d",
  "input.background": "#161b22",
  "input.foreground": "#c9d1d9",
  "input.border": "#30363d",
  "button.background": "#2f81f7",
  "button.foreground": "#ffffff",
  "button.secondaryBackground": "#21262d",
  "button.secondaryForeground": "#c9d1d9",
  "dropdown.background": "#161b22",
  "dropdown.border": "#30363d",
  "editorWidget.background": "#161b22",
  "list.hoverBackground": "#161b22",
  "list.activeSelectionBackground": "#1f6feb",
  "list.activeSelectionForeground": "#ffffff",
  "activityBar.background": "#010409",
  "activityBar.foreground": "#f0f6fc",
  "statusBar.background": "#161b22",
  "statusBar.foreground": "#c9d1d9",
  "titleBar.activeBackground": "#0d1117",
  "titleBar.activeForeground": "#c9d1d9",
  "terminal.background": "#0d1117",
  "terminal.foreground": "#c9d1d9",
  "terminal.selectionBackground": "#264f78",
  "terminalCursor.foreground": "#c9d1d9",
  "editorLineNumber.foreground": "#6e7681",
  "editorGutter.addedBackground": "#3fb950",
  "editorGutter.modifiedBackground": "#2f81f7",
  "editorGutter.deletedBackground": "#f85149",
  "textLink.foreground": "#58a6ff",
  "badge.background": "#30363d",
  "badge.foreground": "#f0f6fc",
};

const GITHUB_DARK_DIMMED_COLORS: VsCodeThemeColors = {
  foreground: "#adbac7",
  descriptionForeground: "#768390",
  "editor.background": "#22272e",
  "editor.foreground": "#adbac7",
  "sideBar.background": "#1c2128",
  "sideBar.foreground": "#adbac7",
  "panel.background": "#22272e",
  "panel.border": "#373e47",
  "input.background": "#2d333b",
  "input.foreground": "#adbac7",
  "input.border": "#444c56",
  "button.background": "#539bf5",
  "button.foreground": "#ffffff",
  "button.secondaryBackground": "#373e47",
  "button.secondaryForeground": "#adbac7",
  "dropdown.background": "#2d333b",
  "dropdown.border": "#444c56",
  "editorWidget.background": "#2d333b",
  "list.hoverBackground": "#2d333b",
  "list.activeSelectionBackground": "#316dca",
  "list.activeSelectionForeground": "#ffffff",
  "activityBar.background": "#1c2128",
  "activityBar.foreground": "#adbac7",
  "statusBar.background": "#22272e",
  "statusBar.foreground": "#adbac7",
  "titleBar.activeBackground": "#22272e",
  "titleBar.activeForeground": "#adbac7",
  "terminal.background": "#22272e",
  "terminal.foreground": "#adbac7",
  "terminal.selectionBackground": "#264f78",
  "terminalCursor.foreground": "#adbac7",
  "editorLineNumber.foreground": "#636e7b",
  "editorGutter.addedBackground": "#57ab5a",
  "editorGutter.modifiedBackground": "#539bf5",
  "editorGutter.deletedBackground": "#e5534b",
  "textLink.foreground": "#539bf5",
  "badge.background": "#444c56",
  "badge.foreground": "#f0f6fc",
};

const ONE_DARK_PRO_COLORS: VsCodeThemeColors = {
  foreground: "#abb2bf",
  descriptionForeground: "#7f848e",
  "editor.background": "#282c34",
  "editor.foreground": "#abb2bf",
  "sideBar.background": "#21252b",
  "sideBar.foreground": "#abb2bf",
  "panel.background": "#282c34",
  "panel.border": "#3b4048",
  "input.background": "#1e2228",
  "input.foreground": "#abb2bf",
  "input.border": "#3b4048",
  "button.background": "#61afef",
  "button.foreground": "#0b0f14",
  "button.secondaryBackground": "#2c313c",
  "button.secondaryForeground": "#abb2bf",
  "dropdown.background": "#21252b",
  "dropdown.border": "#3b4048",
  "editorWidget.background": "#21252b",
  "list.hoverBackground": "#2c313c",
  "list.activeSelectionBackground": "#3e4451",
  "list.activeSelectionForeground": "#ffffff",
  "activityBar.background": "#21252b",
  "activityBar.foreground": "#d7dae0",
  "statusBar.background": "#21252b",
  "statusBar.foreground": "#abb2bf",
  "titleBar.activeBackground": "#282c34",
  "titleBar.activeForeground": "#abb2bf",
  "terminal.background": "#282c34",
  "terminal.foreground": "#abb2bf",
  "terminal.selectionBackground": "#3e4451",
  "terminalCursor.foreground": "#61afef",
  "editorLineNumber.foreground": "#636d83",
  "editorGutter.addedBackground": "#98c379",
  "editorGutter.modifiedBackground": "#e5c07b",
  "editorGutter.deletedBackground": "#e06c75",
  "textLink.foreground": "#61afef",
  "badge.background": "#3e4451",
  "badge.foreground": "#ffffff",
};

const MONOKAI_COLORS: VsCodeThemeColors = {
  foreground: "#f8f8f2",
  descriptionForeground: "#b6b6aa",
  "editor.background": "#272822",
  "editor.foreground": "#f8f8f2",
  "sideBar.background": "#1e1f1c",
  "sideBar.foreground": "#f8f8f2",
  "panel.background": "#272822",
  "panel.border": "#414339",
  "input.background": "#3b3a32",
  "input.foreground": "#f8f8f2",
  "input.border": "#5b5c57",
  "button.background": "#66d9ef",
  "button.foreground": "#1a1b17",
  "button.secondaryBackground": "#414339",
  "button.secondaryForeground": "#f8f8f2",
  "dropdown.background": "#3b3a32",
  "dropdown.border": "#5b5c57",
  "editorWidget.background": "#1e1f1c",
  "list.hoverBackground": "#3b3a32",
  "list.activeSelectionBackground": "#49483e",
  "list.activeSelectionForeground": "#f8f8f2",
  "activityBar.background": "#1e1f1c",
  "activityBar.foreground": "#f8f8f2",
  "statusBar.background": "#414339",
  "statusBar.foreground": "#f8f8f2",
  "titleBar.activeBackground": "#272822",
  "titleBar.activeForeground": "#f8f8f2",
  "terminal.background": "#272822",
  "terminal.foreground": "#f8f8f2",
  "terminal.selectionBackground": "#49483e",
  "terminalCursor.foreground": "#f8f8f2",
  "editorLineNumber.foreground": "#90908a",
  "editorGutter.addedBackground": "#a6e22e",
  "editorGutter.modifiedBackground": "#e6db74",
  "editorGutter.deletedBackground": "#f92672",
  "textLink.foreground": "#66d9ef",
  "badge.background": "#5b5c57",
  "badge.foreground": "#f8f8f2",
};

const SOLARIZED_DARK_COLORS: VsCodeThemeColors = {
  foreground: "#839496",
  descriptionForeground: "#72898f",
  "editor.background": "#002b36",
  "editor.foreground": "#839496",
  "sideBar.background": "#073642",
  "sideBar.foreground": "#839496",
  "panel.background": "#002b36",
  "panel.border": "#17454f",
  "input.background": "#073642",
  "input.foreground": "#839496",
  "input.border": "#17454f",
  "button.background": "#268bd2",
  "button.foreground": "#fdf6e3",
  "button.secondaryBackground": "#17454f",
  "button.secondaryForeground": "#93a1a1",
  "dropdown.background": "#073642",
  "dropdown.border": "#17454f",
  "editorWidget.background": "#073642",
  "list.hoverBackground": "#0b3a47",
  "list.activeSelectionBackground": "#0f4c5c",
  "list.activeSelectionForeground": "#fdf6e3",
  "activityBar.background": "#073642",
  "activityBar.foreground": "#93a1a1",
  "statusBar.background": "#073642",
  "statusBar.foreground": "#93a1a1",
  "titleBar.activeBackground": "#002b36",
  "titleBar.activeForeground": "#93a1a1",
  "terminal.background": "#002b36",
  "terminal.foreground": "#839496",
  "terminal.selectionBackground": "#0f4c5c",
  "terminalCursor.foreground": "#268bd2",
  "editorLineNumber.foreground": "#586e75",
  "editorGutter.addedBackground": "#859900",
  "editorGutter.modifiedBackground": "#b58900",
  "editorGutter.deletedBackground": "#dc322f",
  "textLink.foreground": "#268bd2",
  "badge.background": "#17454f",
  "badge.foreground": "#93a1a1",
};

export const VSCODE_THEME_PRESETS: Record<
  ThemePresetId,
  VsCodeThemePresetDefinition
> = {
  "vscode-dark-modern": {
    id: "vscode-dark-modern",
    appearance: "dark",
    labelKey: "settings.themePresetDarkModern",
    colors: DARK_MODERN_COLORS,
  },
  "vscode-dark-plus": {
    id: "vscode-dark-plus",
    appearance: "dark",
    labelKey: "settings.themePresetDarkPlus",
    colors: DARK_PLUS_COLORS,
  },
  "vscode-light-modern": {
    id: "vscode-light-modern",
    appearance: "light",
    labelKey: "settings.themePresetLightModern",
    colors: LIGHT_MODERN_COLORS,
  },
  "vscode-light-plus": {
    id: "vscode-light-plus",
    appearance: "light",
    labelKey: "settings.themePresetLightPlus",
    colors: LIGHT_PLUS_COLORS,
  },
  "vscode-github-light": {
    id: "vscode-github-light",
    appearance: "light",
    labelKey: "settings.themePresetGitHubLight",
    colors: GITHUB_LIGHT_COLORS,
  },
  "vscode-solarized-light": {
    id: "vscode-solarized-light",
    appearance: "light",
    labelKey: "settings.themePresetSolarizedLight",
    colors: SOLARIZED_LIGHT_COLORS,
  },
  "vscode-github-dark": {
    id: "vscode-github-dark",
    appearance: "dark",
    labelKey: "settings.themePresetGitHubDark",
    colors: GITHUB_DARK_COLORS,
  },
  "vscode-github-dark-dimmed": {
    id: "vscode-github-dark-dimmed",
    appearance: "dark",
    labelKey: "settings.themePresetGitHubDarkDimmed",
    colors: GITHUB_DARK_DIMMED_COLORS,
  },
  "vscode-one-dark-pro": {
    id: "vscode-one-dark-pro",
    appearance: "dark",
    labelKey: "settings.themePresetOneDarkPro",
    colors: ONE_DARK_PRO_COLORS,
  },
  "vscode-monokai": {
    id: "vscode-monokai",
    appearance: "dark",
    labelKey: "settings.themePresetMonokai",
    colors: MONOKAI_COLORS,
  },
  "vscode-solarized-dark": {
    id: "vscode-solarized-dark",
    appearance: "dark",
    labelKey: "settings.themePresetSolarizedDark",
    colors: SOLARIZED_DARK_COLORS,
  },
};

export function getVsCodeThemePreset(
  presetId: ThemePresetId,
): VsCodeThemePresetDefinition {
  return VSCODE_THEME_PRESETS[presetId];
}
